// ─── Color palette ─────────────────────────────────────────────────────────
export const C = {
  canvas:    '#F7F5EF',
  primary:   '#21644A',
  darkText:  '#1E2822',
  softGreen: '#E4F0E8',
  deepGreen: '#164534',
  gold:      '#D79A32',
  border:    '#DDD8CD',
  muted:     '#667169',
  success:   '#3D8D62',
  error:     '#B84A4A',
  white:     '#FFFFFF',
  cardShadow: '0 1px 3px rgba(30,40,34,0.06), 0 4px 16px rgba(30,40,34,0.05)',
};

// ─── Mock Kabadiwala data ──────────────────────────────────────────────────
export const KABADIWALAS = [
  {
    id: 'greencycle',
    name: 'GreenCycle Kabadiwala',
    initials: 'GC',
    verified: true,
    rating: 4.8,
    reviews: 127,
    distance: '1.2 km',
    distanceNum: 1.2,
    availability: 'Available today',
    availableToday: true,
    materials: ['PET Plastic', 'Cardboard', 'Aluminium'],
    matchScore: 94,
    estimatedOffer: '₹310–₹340',
    whyMatch: 'Closest verified PET specialist available today.',
    deals: 342,
    joinedYear: 2019,
    location: 'Malviya Nagar, Jaipur',
    recentReviews: [
      { author: 'Sunita Agarwal', company: 'Apex Traders', text: 'Very professional, fair pricing, quick process.', rating: 5 },
      { author: 'Manoj Verma', company: 'TechWaste Pvt Ltd', text: 'Reliable and knowledgeable. Highly recommended.', rating: 5 },
      { author: 'Priya Menon', company: 'GreenOffice Co.', text: 'Great experience, transparent pricing every time.', rating: 4 },
    ],
  },
  {
    id: 'ecoking',
    name: 'EcoKing Recyclers',
    initials: 'EK',
    verified: true,
    rating: 4.5,
    reviews: 89,
    distance: '2.8 km',
    distanceNum: 2.8,
    availability: 'Available today',
    availableToday: true,
    materials: ['PET Plastic', 'Glass', 'Paper'],
    matchScore: 81,
    estimatedOffer: '₹290–₹320',
    whyMatch: 'Verified PET handler with a strong availability record.',
    deals: 210,
  },
  {
    id: 'jaipur-scrap',
    name: 'Jaipur Scrap Hub',
    initials: 'JS',
    verified: false,
    rating: 4.1,
    reviews: 53,
    distance: '3.5 km',
    distanceNum: 3.5,
    availability: 'Available in 2 days',
    availableToday: false,
    materials: ['PET Plastic', 'Metal', 'E-Waste'],
    matchScore: 72,
    estimatedOffer: '₹270–₹300',
    whyMatch: 'Handles PET plastic but limited availability this week.',
    deals: 98,
  },
  {
    id: 'savera',
    name: 'Savera Kabadiwala',
    initials: 'SK',
    verified: true,
    rating: 4.6,
    reviews: 104,
    distance: '4.1 km',
    distanceNum: 4.1,
    availability: 'Available today',
    availableToday: true,
    materials: ['Cardboard', 'Paper', 'Aluminium'],
    matchScore: 58,
    estimatedOffer: '₹250–₹280',
    whyMatch: 'High rating but does not specialise in PET plastic.',
    deals: 187,
  },
  {
    id: 'rajasthan',
    name: 'Rajasthan RecycleMart',
    initials: 'RR',
    verified: true,
    rating: 3.9,
    reviews: 31,
    distance: '6.7 km',
    distanceNum: 6.7,
    availability: 'Available tomorrow',
    availableToday: false,
    materials: ['PET Plastic', 'Cardboard'],
    matchScore: 47,
    estimatedOffer: '₹240–₹270',
    whyMatch: 'Accepts PET plastic but further away with lower rating.',
    deals: 62,
  },
];

// inputStyle is exported from components/ui; this duplicate is kept for backwards compat
export const inputStyle: import('react').CSSProperties = {
  padding: '10px 14px', borderRadius: 8, border: `1.5px solid ${C.border}`,
  fontSize: 14, color: C.darkText, background: C.white,
  transition: 'border-color 0.15s, box-shadow 0.15s',
};
